
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8

compiler:
  - clang
  - gcc

before_script:
  - cd test
  - make

script:
  - make run
